### ISSUE TITLE
Importing DataUtilities.ClearDataMode yields unresolved import

### ISSUE THREAD

**Issue by astrelsky** [VDOO-Connected-Trust/ghidra-pyi-generator#4]
First off great job with this. I just added the extracted files to the root folder of my own pythonUtils which is on my systems PYTHONPATH, loaded up vscode and worked as soon as I added `import ghidra` and the try/except for the builtins.

This is the following line I have which works fine when the script is run in ghidra.
`from ghidra.program.model.data.DataUtilities.ClearDataMode import CLEAR_ALL_CONFLICT_DATA`

It doesn't seem to allow the import of the ClearDataMode static class.
The following does work but I'd prefer the above since it is shorter:
```
from ghidra.program.model.data.DataUtilities import ClearDataMode
def createClass(address, dt):
    return DataUtilities.createData(currentProgram, address, dt,
                            dt.getLength(), False, ClearDataMode.CLEAR_ALL_CONFLICT_DATA)
```

Edit: it appears if I just import `from ghidra.program.model.data import DataUtilities`
 it is expecting `DataUtilities.DataUtilities.ClearDataMode.CLEAR_ALL_CONFLICT_DATA`

**Comment by tmr232** [comment]
This seems to be an issue with nested classes. While Java, and therefore Jython, allow importing nested classes, Python does not.
To solve this issue, we need to come up with a workaround to imitate the same behavior in standard CPython. Presently, I don't have a way to resolve this.

**Comment by astrelsky** [comment]
> This seems to be an issue with nested classes. While Java, and therefore Jython, allow importing nested classes, Python does not.
> To solve this issue, we need to come up with a workaround to imitate the same behavior in standard CPython. Presently, I don't have a way to resolve this.

I see. If I come up with any ideas I'll bring them up then.
