### ISSUE TITLE
How to use Python to analysis binary file

### ISSUE THREAD

**Issue by EmpRamses** [VDOO-Connected-Trust/ghidra-pyi-generator#7]
Excellent Work! But how can I get the analyzed code handler just like the currentProgram in ghidra's jython interpreter?

**Comment by tmr232** [comment]
```python
try:
    from ghidra_builtins import *
except:
    pass
```

Should do the trick. See [here](https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator#using-the-stubs).
